### ISSUE TITLE
希望可以提供配置开关，关闭“我不知道你要摸谁”提示

### ISSUE THREAD

**Issue by MR-MonkeyRay** [LaoLittle/DrawMeme#5]
RT

**Comment by LaoLittle** [comment]
我觉得可以直接删除提示

**Comment by MR-MonkeyRay** [comment]
我也觉得可以干掉提示了😂
现在经常大伙在"摸鱼"的时候,就突然蹦出来"不知道要摸谁"

**Comment by LaoLittle** [comment]
[release 1.2.3](https://github.com/LaoLittle/DrawMeme/releases/tag/1.2.3)
