### ISSUE TITLE
重构计划

### ISSUE THREAD

**Issue by LaoLittle** [LaoLittle/DrawMeme#6]
为了能够更好的进行二次开发以及管理和方便使用，计划进行重构

- [ ] 为每个meme单独提供一份权限表，可选择群聊开启（或由console权限系统接管）
- [ ] 每个meme单独作为一个对象，抽象meme以便二次开发
- [ ] 自动生成meme帮助和示例
- [ ] 资源文件应由更好的方式提供
- [ ] 提供详尽的错误处理和错误信息
- [ ] 添加readme和使用文档

**Comment by SisCleaire** [comment]
期待权限系统

**Comment by LaoLittle** [comment]
> 期待权限系统

https://github.com/LaoLittle/atri_qq
最近在整这个，所以可能得鸽了
